### ISSUE TITLE
error installation : No module named '_curses'

### ISSUE THREAD

**Issue by lolminerxmrig01** [coffinxp/loxs#71]
Hi.
plz help me fixed Error: 

![image](https://github.com/user-attachments/assets/274473c6-678e-4a9c-b83b-5072e6db6d03)

not working : pip install windows-curses

![image](https://github.com/user-attachments/assets/82b3dbc4-08bd-43e0-b0d8-7910421e1013)

**Comment by HexShad0w** [comment]
Hello,

The error happens because curses is unavailable on Windows

--> Ensure you're using Python 3.6–3.10, as windows-curses doesn’t support other versions. 

Check your version using:

• python --version

--> Then try installing Windows-curses again:

• pip install windows-curses

Best Regards,
hexsh1dow

**Comment by lolminerxmrig01** [comment]
python -V
Python 3.13.1

**Comment by HexShad0w** [comment]
Hello,

**Currently the latest version of windows-curses is 2.4.0 and it provides wheels for Python 3.6-3.10.**

**So basically you either have to downgrade your Python installation**

--> I never had this problem, here is a good/logical solution, it should work.

Note : When you encounter a problem like this, there are usually stackoverflow questions that help you find a solution to your problem.

```bash
https://stackoverflow.com/questions/77423447/cant-install-curses-package 
```

```bash
https://pypi.org/project/windows-curses/
```
Best Regards,
hexsh1dow
